name: ktemplate
description: A Kitawi app
version: 1.0.0
publish_to: none

environment:
  sdk: "3.0.0-417.2.beta"

dependencies:
  kitawi: 0.0.9
dev_dependencies:
  build_runner: ^2.3.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
